--liquibase formatted sql

--changeset estinca:inventory-001
--comment: create product inventory balances
CREATE TABLE inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id UUID NOT NULL UNIQUE,
    available_quantity INT NOT NULL DEFAULT 0,
    reserved_quantity INT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_inventory_available_quantity CHECK (available_quantity >= 0),
    CONSTRAINT chk_inventory_reserved_quantity CHECK (reserved_quantity >= 0)
);

--changeset estinca:inventory-002
--comment: create inventory reservations and their product lines
CREATE TABLE inventory_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    order_id UUID NOT NULL UNIQUE,
    status VARCHAR(32) NOT NULL,
    failure_reason VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE inventory_reservation_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    reservation_id BIGINT NOT NULL,
    product_id UUID NOT NULL,
    quantity INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_inventory_reservation_items_reservation FOREIGN KEY (reservation_id) REFERENCES inventory_reservations(id),
    CONSTRAINT chk_inventory_reservation_quantity CHECK (quantity > 0),
    CONSTRAINT ux_inventory_reservation_product UNIQUE (reservation_id, product_id)
);
CREATE INDEX idx_inventory_reservation_items_reservation_id
    ON inventory_reservation_items(reservation_id);

--changeset estinca:inventory-003
--comment: add transactional outbox and idempotent message inbox
CREATE TABLE event_outbox (
    event_id UUID PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    routing_key VARCHAR(150) NOT NULL,
    payload TEXT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ,
    locked_at TIMESTAMPTZ,
    attempts INT NOT NULL DEFAULT 0,
    last_error VARCHAR(500)
);
CREATE INDEX idx_inventory_outbox_pending
    ON event_outbox(occurred_at)
    WHERE published_at IS NULL;

CREATE TABLE inbox_messages (
    event_id UUID PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL
);
