--liquibase formatted sql

--changeset estinca:notifications-001
--comment: create durable notification delivery records
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    source_event_id UUID NOT NULL UNIQUE,
    order_id UUID NOT NULL,
    customer_id UUID NOT NULL,
    type VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL,
    message VARCHAR(500) NOT NULL,
    attempts INT NOT NULL DEFAULT 0,
    last_error VARCHAR(500),
    next_attempt_at TIMESTAMPTZ NOT NULL,
    locked_at TIMESTAMPTZ,
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_notifications_customer_created
    ON notifications(customer_id, created_at DESC);
CREATE INDEX idx_notifications_pending
    ON notifications(next_attempt_at, created_at)
    WHERE status IN ('PENDING', 'FAILED');

--changeset estinca:notifications-002
--comment: add idempotent order event inbox
CREATE TABLE inbox_messages (
    event_id UUID PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL
);
