--liquibase formatted sql

--changeset estinca:products-003
--comment: let PostgreSQL generate product persistence identifiers
ALTER TABLE products
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
    pg_get_serial_sequence('products', 'id'),
    COALESCE((SELECT MAX(id) FROM products), 0) + 1,
    false
);
