--liquibase formatted sql

--changeset estinca:customers-001
--comment: create customer profiles
CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    email VARCHAR(320) NOT NULL,
    phone VARCHAR(32),
    email_notifications_enabled BOOLEAN NOT NULL,
    sms_notifications_enabled BOOLEAN NOT NULL,
    event_version BIGINT NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
CREATE UNIQUE INDEX uq_customers_email_lower ON customers(lower(email));

--changeset estinca:customers-002
--comment: create transactional customer event outbox
CREATE TABLE event_outbox (
    event_id UUID PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    exchange_name VARCHAR(150) NOT NULL,
    routing_key VARCHAR(150) NOT NULL,
    payload TEXT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ,
    locked_at TIMESTAMPTZ,
    attempts INT NOT NULL DEFAULT 0,
    last_error VARCHAR(500)
);
CREATE INDEX idx_customer_outbox_pending ON event_outbox(occurred_at) WHERE published_at IS NULL;
