--liquibase formatted sql

--changeset estinca:001
--comment: create carts table
CREATE TABLE IF NOT EXISTS carts (
     id BIGINT PRIMARY KEY,
     public_id UUID NOT NULL UNIQUE,
     customer_id UUID,
     status VARCHAR(32) NOT NULL,
     created_at TIMESTAMPTZ NOT NULL,
     updated_at TIMESTAMPTZ NOT NULL
);

--changeset estinca:002
--comment: create cart_items table
CREATE TABLE IF NOT EXISTS cart_items (
     id BIGINT PRIMARY KEY,
     public_id UUID NOT NULL UNIQUE,
     cart_id BIGINT NOT NULL,
     product_id BIGINT NOT NULL,
     product_sku VARCHAR(64) NOT NULL,
     product_name VARCHAR(160) NOT NULL,
     unit_price_amount NUMERIC(12, 2) NOT NULL,
     currency VARCHAR(3) NOT NULL,
     quantity INT NOT NULL,
     created_at TIMESTAMPTZ NOT NULL,
     updated_at TIMESTAMPTZ NOT NULL,

     constraint fk__cart_id foreign key (cart_id) references carts(id)
);

--changeset estinca:003
--comment: add database-generated internal identifiers
ALTER TABLE carts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
--rollback ALTER TABLE cart_items ALTER COLUMN id DROP IDENTITY IF EXISTS;
--rollback ALTER TABLE carts ALTER COLUMN id DROP IDENTITY IF EXISTS;

--changeset estinca:004
--comment: store the catalog public product identifier
ALTER TABLE cart_items DROP COLUMN product_id;
ALTER TABLE cart_items ADD COLUMN product_id UUID NOT NULL;
--rollback ALTER TABLE cart_items DROP COLUMN product_id;
--rollback ALTER TABLE cart_items ADD COLUMN product_id BIGINT NOT NULL;

--changeset estinca:005
--comment: enforce one active cart per customer and one item per product
CREATE UNIQUE INDEX ux_carts_active_customer
    ON carts(customer_id)
    WHERE status = 'ACTIVE' AND customer_id IS NOT NULL;
CREATE UNIQUE INDEX ux_cart_items_cart_product
    ON cart_items(cart_id, product_id);
--rollback DROP INDEX IF EXISTS ux_cart_items_cart_product;
--rollback DROP INDEX IF EXISTS ux_carts_active_customer;
