--liquibase formatted sql

--changeset estinca:001
--comment: create orders table
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    source_cart_id UUID NOT NULL UNIQUE,
    customer_id UUID NOT NULL,
    status VARCHAR(32) NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_orders_customer_id ON orders(customer_id);

--changeset estinca:002
--comment: create immutable order item snapshots
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    order_id BIGINT NOT NULL,
    product_id UUID NOT NULL,
    product_sku VARCHAR(64) NOT NULL,
    product_name VARCHAR(160) NOT NULL,
    unit_price_amount NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    quantity INT NOT NULL,
    line_total_amount NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT chk_order_items_quantity CHECK (quantity BETWEEN 1 AND 99)
);
CREATE INDEX idx_order_items_order_id ON order_items(order_id);
